# TODO: Go here for detailed information on Application Service configuration:
#       https://docs.edgexfoundry.org/latest/microservices/application/GeneralAppServiceConfig/
Writable:
  LogLevel: "INFO"

  Telemetry:
    Metrics: # All service's metric private configuration metrics must be listed here.
      # TODO: Remove sample custom metric and implement meaningful custom metrics if any needed.
      # Custom App Service Metrics
      EventsConvertedToXML: true

Service:
  Host: localhost
  Port: 59741
  StartupMsg: "edgex-app-template Application Service has started"

# TODO: Remove section if not using HTTPS Webserver. Default protocol is HTTP if section is empty
HttpServer:
  Protocol: "http"
  SecretName: "https"
  HTTPSCertName: "cert"
  HTTPSKeyName: "key"

Clients:
  core-data:
    Protocol: "http"
    Host: "localhost"
    Port: 59880

  support-notifications:
    Protocol: "http"
    Host: "localhost"
    Port: 59860

MessageBus:
  Disabled: false # TODO: set to true if not using edgex-messagebus Trigger below and don't want Metrics or Commands via MessageBus
  Optional:
    ClientId: "edgex-app-template"

Trigger:
  # Note that the MessageBus connection above is used by edgex-messagebus trigger which is the default set in common config
  # Default value for SubscribeTopics is aslo set in common config
  PublishTopic: "application" # Base topic is prepened to this topic when using edgex-messagebus
  SubscribeTopics: "events/#"
